# Generated by Django 3.1.7 on 2021-04-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='blue_flag_temp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='blue_flagadd_temp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='kyc_infotemp',
            name='red_flag_temp',
            field=models.CharField(max_length=5),
        ),
    ]
