# Generated by Django 3.1.7 on 2021-04-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20210410_1830'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kyc_infotemp',
            table='details',
        ),
    ]
