# Generated by Django 3.1.7 on 2021-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_infotemp_id_red_flag_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_infotemp',
            name='iddob_blue_flag_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kyc_infotemp',
            name='idname_blue_flag_temp',
            field=models.BooleanField(default=False),
        ),
    ]
