# Generated by Django 3.1.7 on 2021-03-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_info_nics_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc_info',
            name='occu_state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
