# Generated by Django 3.1.7 on 2021-04-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20210411_0040'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kyc_infotemp',
            table=None,
        ),
    ]
