# Generated by Django 3.1.7 on 2021-04-10 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kyc_infotemp_id_type_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_info',
            name='birth_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d'),
            preserve_default=False,
        ),
    ]
