# Generated by Django 3.1.7 on 2021-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_id_info_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_info',
            name='city_ref',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='id_info',
            name='house_num',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='id_info',
            name='street_add',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
