# Generated by Django 3.1.7 on 2021-04-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_auto_20210410_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc_info',
            name='country',
        ),
        migrations.RemoveField(
            model_name='kyc_infotemp',
            name='country_temp',
        ),
    ]
