# Generated by Django 3.1.7 on 2021-04-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_auto_20210411_1344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kyc_infotemp',
            table='details',
        ),
    ]
