# Generated by Django 3.1.7 on 2021-04-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_auto_20210412_0838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kyc_infotemp',
            table='kyc_tempdetails',
        ),
    ]
