# Generated by Django 3.1.7 on 2021-04-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0012_auto_20210412_0853'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kyc_infotemp',
            table='details',
        ),
    ]
