# Generated by Django 3.1.7 on 2021-03-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_web', '0002_kycinfo_long_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='phone_num',
            field=models.CharField(max_length=12),
        ),
    ]
